### ISSUE TITLE
Separate default and override.yml file.

### ISSUE THREAD

**Issue by ryanhamilton** [webcompere/lightweight-config#12]
Hi,

I want my users to be able to set configuration in a .yml file.
Currently I seem to need to specify the env/system properties in the same YML file that I expose to users.

I want to allow my users to override the handful of parameters they want in the .yml file
WITHOUT them seeing or being able to affect the env variables.

### Example:

Internal-default.yml
```
auth_proxy_enabled: ${AUTH_PROXY_ENABLED:-"true"}
username_header_name: ${HEADER_NAME:-"X-WEBAUTH-USER"}
```

user-config.yml
```
# auth_proxy_enabled:false
username_header_name:myheader
```

This should result in 
auth_proxy_enabled = true UNLESS system/env variables et.
username_header_name = myheader.

I think this means the order:
1. Environment variable
2. System property
3. **Override .YML**
4. Default .YML
5. Blank

Is my request clear?
Is it something you think should be added to this project? 
If not can you advise on a more suitable library?

Thanks,
Ryan

**Comment by ashleyfrieze** [comment]
I wonder whether you can handle this using imports?

https://github.com/webcompere/lightweight-config#importing-other-files

If your default yml file did an import of the user file at the end, then the user settings could be used to replace the defaults...?

**Comment by ashleyfrieze** [comment]
@ryanhamilton - did the above work for you? If so, we may want to extend the docs. If not, let's see how close it gets and how we can extend the library to complete the journey.

**Comment by ashleyfrieze** [comment]
I'm closing this on the basis that there is some feature support for importing and the trail has gone cold on this discussion.
